//----------------------------------------------------------------------//
// Arrays used to create Divs/Buttons    
//----------------------------------------------------------------------//

const divPlyer = ["rules","player_1","player_2"]
const divPlyerButton = ["btn-rules","btn-player_1","btn-player_2"]
const divRound = ["","",""]
const divPlayers = ["div_player_1","ready","back"]
const btnPlayers = ["upt-player","btn-ready_1","btn-back"]
const playingID = ["timers","round-timer","game-player","player-score"]
const inputCategories = ["animal_1","color_1","state_1","country_1","score_1"]
const liCategoriesChanged = ["animal_0","color_0","state_0","country_0","score_0"]
const idCategories = ["animal","color","state","country","score"]
const olCategories = ["ol-animal","ol-color","ol-state","ol-country","ol-score"]
const liNewCategories = ["li-animal","li-color","li-state","li-country","li-score"]
const liOldCategories = ["li-animal_1","li-color_1","li-state_1","li-country_1","li-score_1"]
const buttonPlayers = ["RULES","PL vs CP", "PL vs PL"]




//----------------------------------------------------------------------//
// DB  - ANIMALS - ENGLISH   
//----------------------------------------------------------------------//

const animalCategory = [
// LETTER - A",
"AARDVARK","AARDWOLF","ABYSSINIAN","ACHRIOPTERA MANGA","ADDAX","ADELIE PENGUIN","AESCULAPIAN SNAKE","AFFENPINSCHER","AFGHAN HOUND","AFRICAN BULLFROG","AFRICAN BUSH ELEPHANT","AFRICAN CIVET","AFRICAN CLAWED FROG","AFRICAN FOREST ELEPHANT","AFRICAN GREY PARROT","AFRICAN PALM CIVET","AFRICAN PENGUIN","AFRICAN TREE TOAD","AFRICAN WILD DOG","AGAMA LIZARD","AIDI","AINU","AIREDALE TERRIER","AIREDOODLE","AKBASH","AKITA","AKITA SHEPHERD","ALABAI","ALASKAN HUSKY","ALASKAN KLEE KAI","ALASKAN MALAMUTE","ALASKAN POLLOCK","ALASKAN SHEPHERD","ALBACORE TUNA","ALBATROSS","ALDABRA GIANT TORTOISE","ALLIGATOR","ALLIGATOR GAR","ALLOSAURUS","ALPACA","ALPINE DACHSBRACKE","ALPINE GOAT","ALUSKY","AMARGASAURUS","AMAZON PARROT","AMAZON RIVER DOLPHIN (PINK DOLPHIN)","AMBROSIA BEETLE","AMERICAN ALSATIAN","AMERICAN BULLDOG","AMERICAN COCKER SPANIEL","AMERICAN COCKROACH","AMERICAN COONHOUND","AMERICAN DOG TICK","AMERICAN ESKIMO DOG","AMERICAN FOXHOUND","AMERICAN HAIRLESS TERRIER","AMERICAN LEOPARD HOUND","AMERICAN PIT BULL TERRIER","AMERICAN PYGMY GOAT","AMERICAN ROBIN","AMERICAN STAFFORDSHIRE TERRIER","AMERICAN TOAD","AMERICAN WATER SPANIEL","AMETHYSTINE PYTHON","AMUR LEOPARD","ANACONDA","ANATOLIAN SHEPHERD DOG","ANCHOVIES","ANGELFISH","ANGLERFISH","ANGORA FERRET","ANGORA GOAT","ANOLE LIZARD","ANOMALOCARIS","ANT","ANTARCTIC SCALE WORM","ANTEATER","ANTELOPE","APE","APPENZELLER DOG","APPLE HEAD CHIHUAHUA","APPLE MOTH","ARABIAN COBRA","ARAFURA FILE SNAKE","ARAPAIMA","ARCHAEOPTERYX","ARCHAEOTHERIUM","ARCHELON TURTLE","ARCTIC FOX","ARCTIC HARE","ARCTIC WOLF","ARCTODUS","ARCTOTHERIUM","ARIZONA BARK SCORPION","ARIZONA BLACK RATTLESNAKE","ARIZONA CORAL SNAKE","ARMADILLO","ARMADILLO LIZARD","ARMYWORM","ARUBA RATTLESNAKE","ASIAN AROWANA","ASIAN COCKROACH","ASIAN ELEPHANT","ASIAN GIANT HORNET","ASIAN PALM CIVET","ASIAN VINE SNAKE","ASIATIC BLACK BEAR","ASP","ASSASSIN BUG","ATLANTIC SALMON","ATLAS MOTH","AUROCHS","AUSSIEDOODLE","AUSSIEDOR","AUSTRALIAN BULLDOG","AUSTRALIAN CATTLE DOG","AUSTRALIAN COCKROACH","AUSTRALIAN FLATHEAD PERCH","AUSTRALIAN GECKO","AUSTRALIAN KELPIE DOG","AUSTRALIAN LABRADOODLE","AUSTRALIAN MIST","AUSTRALIAN RETRIEVER","AUSTRALIAN SHEPHERD","AUSTRALIAN TERRIER","AUSTRALOPITHECUS","AVOCET","AXOLOTL","AYE AYE",    
    // LETTER - B
"BABIRUSA", "BABOON", "BACTRIAN CAMEL", "BADGER", "BAIJI", "BAIRD’S RAT SNAKE", "BALD EAGLE", "BALEEN WHALE", "BALINESE", "BALKAN LYNX", "BALL PYTHON", "BAMBOO WORMS", "BANANA BALL PYTHON", "BANANA EEL", "BANANA SPIDER", "BANDED KRAIT", "BANDED PALM CIVET", "BANDED WATER SNAKE", "BANDICOOT", "BANJO CATFISH", "BARB", "BARBET", "BARN OWL", "BARN SWALLOW", "BARNACLE", "BARRACUDA", "BARRAMUNDI FISH", "BARRED OWL", "BASENJI DOG", "BASILISK LIZARD", "BASILOSAURUS", "BASKING SHARK", "BASSADOR", "BASSET FAUVE DE BRETAGNE", "BASSET HOUND", "BASSETOODLE", "BAT", "BATFISH", "BAVARIAN MOUNTAIN HOUND", "BAYA", "BEA-TZU", "BEABULL", "BEAGADOR", "BEAGLE", "BEAGLE SHEPHERD", "BEAGLIER", "BEAGO", "BEAR", "BEARDED COLLIE", "BEARDED DRAGON", "BEARDED VULTURE", "BEASKI", "BEAUCERON", "BEAUTY RAT SNAKE", "BEAVER", "BED BUGS", "BEDLINGTON TERRIER", "BEE", "BEEFALO", "BEETLE", "BELGIAN SHEPHERD", "BELGIAN TERVUREN", "BELUGA STURGEON", "BENGAL TIGER", "BERGAMASCO", "BERGER PICARD", "BERNEDOODLE", "BERNESE MOUNTAIN DOG", "BERNESE SHEPHERD", "BETTA FISH (SIAMESE FIGHTING FISH)", "BICHIR", "BICHON FRISE", "BICHPOO", "BIEWER TERRIER", "BIGHORN SHEEP", "BILBY", "BINTURONG", "BIRD", "BIRD OF PARADISE", "BIRMAN", "BISCUIT BEETLE", "BISON", "BLACK AND TAN COONHOUND", "BLACK MAMBA", "BLACK MARLIN", "BLACK RAT SNAKE", "BLACK RHINOCEROS", "BLACK RUSSIAN TERRIER", "BLACK WASP", "BLACK WIDOW SPIDER", "BLACK WITCH MOTH", 
"BLACK-CAPPED CHICKADEE", "BLACK-FOOTED FERRET", "BLACK-HEADED PYTHON", "BLACKNOSE SHARK", "BLACKPOLL WARBLER", "BLACKTIP REEF SHARK", "BLADEFIN BASSLET", "BLANKET OCTOPUS", "BLIND SNAKE", "BLISTER BEETLE", "BLOBFISH", "BLOOD PYTHON", "BLOODHOUND", "BLUE BELLY LIZARD", "BLUE CATFISH", "BLUE EYED PLECO", "BLUE GRAY GNATCATCHER", "BLUE GROSBEAK", "BLUE IGUANA", "BLUE JAY", "BLUE LACY DOG", "BLUE PICARDY SPANIEL", "BLUE RACER", "BLUE SHARK", "BLUE TIT", "BLUE WHALE", "BLUE-RINGED OCTOPUS", "BLUEFIN TUNA", "BLUEGILL", "BLUETICK COONHOUND", "BOAS", "BOBCAT", "BOBOLINK", "BOELEN’S PYTHON", "BOGGLE", "BOGLEN TERRIER", "BOIGA", "BOLIVIAN ANACONDA", "BOLOGNESE DOG", "BOMBAY", "BONGO", "BONITO FISH", "BONNETHEAD SHARK", "BONOBO", "BOOBY", "BOOMSLANG", "BORADOR", "BORDER COLLIE", "BORDER TERRIER", "BORDOODLE", "BORKIE", "BORNEAN ORANG-UTAN", "BORNEO ELEPHANT", "BOSTON TERRIER", "BOTTLENOSE DOLPHIN", "BOUVIER DES FLANDRES", "BOWFIN", "BOWHEAD WHALE", "BOX TREE MOTH", "BOX TURTLE", "BOXADOR", "BOXER DOG", "BOXERDOODLE", "BOXFISH", "BOXSKY", "BOXWEILER", "BOYKIN SPANIEL", "BRACHIOSAURUS", "BRAHMINY BLINDSNAKE", "BRAZILIAN TERRIER", "BREDL’S PYTHON", "BRITISH TIMBER", "BRITTANY", "BRONTOSAURUS", "BRONZE WHALER SHARK", "BROOKESIA MICRA", "BROWN BEAR", "BROWN DOG TICK", "BROWN HYENA", "BROWN SNAKE", "BROWN WATER SNAKE", "BROWN-BANDED COCKROACH", "BRUG", "BRUSSELS GRIFFON", "BUDGERIGAR", "BUFFALO", "BULL SHARK", "BULL TERRIER", "BULL TROUT", "BULLDOG", "BULLFROG", "BULLMASTIFF", "BULLSNAKE", "BUMBLEBEE", "BURMESE", "BURMESE PYTHON", "BURROWING FROG", "BURROWING OWL", "BUSH BABY", "BUSH VIPER", "BUSHMASTER SNAKE", "BUTTERFLY", "BUTTERFLY FISH",
// LETTER - C
"CABBAGE MOTH", "CACTUS MOTH", "CACTUS MOUSE", "CAECILIAN", "CAIMAN", "CAIMAN LIZARD", "CAIRN TERRIER", "CALIFORNIA KINGSNAKE", "CAMEL", "CAMEL CRICKET", "CAMEL SPIDER", "CANAAN DOG", "CANADA LYNX", "CANADA WARBLER", "CANADIAN ESKIMO DOG", "CANADIAN HORSE", "CANE CORSO", "CANTIL", "CAPE LION", "CAPYBARA", "CARACAL", "CARIBBEAN REEF SHARK", "CARIBOU", "CAROLINA DOG", "CAROLINA PARAKEET", "CARP", "CARPENTER ANT", "CARPET PYTHON", "CARPET VIPER", "CASCABEL", "CASHMERE GOAT", "CASSOWARY", "CAT", "CAT SNAKE", "CAT-EYED SNAKE", "CATAHOULA LEOPARD", "CATALAN SHEEPDOG", "CATERPILLAR", "CATFISH", "CAVA TZU", "CAVADOR", "CAVALIER KING CHARLES SPANIEL", "CAVAPOO", "CAVE BEAR", "CAVE LION", "CECROPIA MOTH", "CENTIPEDE", "CENTRAL RANGES TAIPAN", "CERATOSAURUS", "CESKY FOUSEK", "CESKY TERRIER", "CHAMELEON", "CHAMOIS", "CHARTREUX", "CHEAGLE", "CHECKERED GARTER SNAKE", "CHEETAH", "CHESAPEAKE BAY RETRIEVER", "CHICKADEE", "CHICKEN", "CHICKEN SNAKE", "CHIHUAHUA", "CHILDREN’S PYTHON", "CHIMAERA", "CHIMPANZEE", "CHINCHILLA", "CHINESE ALLIGATOR", "CHINESE COBRA", "CHINESE CRESTED DOG", "CHINESE GEESE", "CHINESE PADDLEFISH", "CHINESE SHAR-PEI", "CHINOOK", "CHINOOK SALMON", "CHINSTRAP PENGUIN", "CHIPMUNK", 
"CHIPOO", "CHIPPING SPARROW", "CHIWEENIE", "CHORKIE", "CHOW CHOW", "CHOW SHEPHERD", "CHRISTMAS ISLAND RED CRAB", "CICADA", "CICHLID", "CINEREOUS VULTURE", "CINNAMON FERRET", "CLOUDED LEOPARD", "CLOWNFISH", "CLUMBER SPANIEL", "COACHWHIP SNAKE", "COASTAL CARPET PYTHON", "COASTAL TAIPAN", "COATI", "COBIA FISH", "COBRAS", "COCKALIER", "COCKAPOO", "COCKATIEL", "COCKATOO", "COCKER SPANIEL", "COCKROACH", "CODFISH", "CODLING MOTH", "COELACANTH", "COLLARED PECCARY", "COLLETT’S SNAKE", "COLLIE", "COLOSSAL SQUID", "COMET MOTH", "COMMON BUZZARD", "COMMON EUROPEAN ADDER", "COMMON FROG", "COMMON FURNITURE BEETLE", "COMMON HOUSE SPIDER", "COMMON LOON", "COMMON RAVEN", "COMMON TOAD", "COMPSOGNATHUS", "CONGER EEL", "CONGO SNAKE", "COOKIECUTTER SHARK", "COOPER’S HAWK", "COPPERHEAD", "CORAL", "CORAL SNAKE", "CORGIDOR", "CORGIPOO", "CORKIE", "CORMAN SHEPHERD", "CORN REX CAT (CORNISH REX)", "CORN SNAKE", "COTON DE TULEAR", "COTTON-TOP TAMARIN", "COTTONMOUTH", "COUGAR", "COW", "COYOTE", "CRAB", "CRAB SPIDER", "CRAB-EATING MACAQUE", "CRABEATER SEAL", "CRANE", "CRAPPIE FISH", "CRESTED GECKO", "CRESTED PENGUIN", "CRICKET", "CROCODILE", "CROSS FOX", "CROSS RIVER GORILLA", "CROW", "CRUCIAN CARP", "CUBAN BOA", "CUBAN COCKROACH", "CUCKOO", "CURLY COATED RETRIEVER", "CUSCUS", "CUTTLEFISH", "CZECHOSLOVAKIAN WOLFDOG",
// LETTER - D
"DACHSADOR", "DACHSHUND", "DAEODON", "DALMADOODLE", "DALMADOR", "DALMATIAN", "DANIOS", "DAPPLE DACHSHUND", "DARWIN’S FOX", "DARWIN’S FROG", "DEATH ADDER", "DEATH’S HEAD COCKROACH", "DEATHWATCH BEETLE", "DEER", "DEER HEAD CHIHUAHUA", "DEER TICK", "DESERT KINGSNAKE", "DESERT LOCUST", "DESERT RAIN FROG", "DESERT TORTOISE", "DEUTSCHE BRACKE", "DEVILS COACH HORSE BEETLE", "DEVON REX", "DHOLE", "DIAMOND PYTHON", "DIAMONDBACK MOTH", "DIK-DIK", "DINGO", "DIPLODOCUS", "DIRE WOLF", "DISCUS", "DOBERMAN PINSCHER", "DODO", "DOG", "DOG TICK", "DOGO ARGENTINO", "DOGUE DE BORDEAUX", "DOLPHIN", "DONKEY", "DORGI", "DORKIE", "DORMOUSE", "DOUBLE DOODLE", "DOUC", "DOXIEPOO", "DOXLE", "DRACO VOLANS LIZARD", "DRAGONFISH", "DRAGONFLY", "DREVER", "DRUM FISH", "DUBIA COCKROACH", "DUCK", "DUGONG", "DUMERIL’S BOA", "DUNG BEETLE", "DUNKER", "DUNNOCK", "DUSKY DOLPHIN", "DUSKY SHARK", "DWARF BOA", "DWARF CROCODILE", "DWARF HAMSTER",
// LETTER - E
"EAGLE", "EARTHWORM", "EARWIG", "EASTERN BARRED BANDICOOT", "EASTERN BLUEBIRD", "EASTERN BROWN SNAKE", "EASTERN CHIPMUNK", "EASTERN CORAL SNAKE", "EASTERN DIAMONDBACK RATTLESNAKE", "EASTERN FENCE LIZARD", "EASTERN GLASS LIZARD", "EASTERN GORILLA", "EASTERN GRAY SQUIRREL", "EASTERN GREEN MAMBA", "EASTERN INDIGO SNAKE", "EASTERN LOWLAND GORILLA", "EASTERN PHOEBE", "EASTERN RACER", "EASTERN RAT SNAKE", "EASTERN WOODRAT", "ECHIDNA", "ECLECTUS PARROT", "EDIBLE FROG", "EEL", "EGYPTIAN COBRA", "EGYPTIAN GOOSE", "EGYPTIAN MAU", "ELAND", "ELASMOSAURUS", "ELASMOTHERIUM", "ELECTRIC CATFISH", "ELECTRIC EEL", "ELEGANT TERN", "ELEPHANT", "ELEPHANT SEAL", "ELEPHANT SHREW", "ELK", "EMERALD TREE MONITOR", "EMPEROR PENGUIN", "EMPEROR TAMARIN", "EMU", "ENGLISH BULLDOG", "ENGLISH COCKER SPANIEL", "ENGLISH CREAM GOLDEN RETRIEVER", "ENGLISH FOXHOUND", "ENGLISH POINTER", "ENGLISH SETTER", "ENGLISH SHEPHERD", "ENGLISH SPRINGER SPANIEL", "ENTLEBUCHER MOUNTAIN DOG", "EPAGNEUL PONT AUDEMER", "EQUATORIAL SPITTING COBRA", "ERMINE", "ESCOLAR", "ESKIMO DOG", "ESKIPOO", "ESTRELA MOUNTAIN DOG", "EURASIAN BEAVER", "EURASIAN JAY", "EURASIAN LYNX", "EURASIAN NUTHATCH", "EURASIAN WOLF", "EUROPEAN BEE-EATER", "EUROPEAN CORN BORER", "EUROPEAN POLECAT", "EUROPEAN ROBIN", "EUROPEAN WILDCAT", "EVENING BAT", "EYELASH VIPER",
// LETTER - F
"FALCON", "FALLOW DEER", "FALSE COBRA", "FALSE CORAL SNAKE", "FALSE KILLER WHALE", "FALSE WATER COBRA", "FALSE WIDOW SPIDER", "FANGTOOTH", "FEIST", "FENNEC FOX", "FER-DE-LANCE SNAKE", "FERRET", "FERRUGINOUS HAWK", "FIDDLER CRAB", "FIELD SPANIEL", "FIERCE SNAKE", "FILA BRASILEIRO", "FIN WHALE", "FINNISH SPITZ", "FIRE EEL", "FIRE SALAMANDER", "FIRE-BELLIED TOAD", "FIREFLY", "FISH", "FISHER CAT", "FISHING CAT", "FLAMINGO", "FLAT-COATED RETRIEVER", "FLEA", "FLORIDA GAR", "FLORIDA PANTHER", "FLORIDA WOODS COCKROACH", "FLOUNDER", "FLOWERHORN FISH", "FLUKE FISH (SUMMER FLOUNDER)", "FLY", "FLYING FISH", "FLYING LEMUR", "FLYING SNAKE", "FLYING SQUIRREL", "FOOTBALL FISH", "FOREST COBRA", "FORMOSAN MOUNTAIN DOG", "FOSSA", "FOX", "FOX SNAKES", "FOX SQUIRREL", "FOX TERRIER", "FRENCH BULLDOG", "FRENCHTON", "FRENGLE", "FRESHWATER CROCODILE", "FRESHWATER EEL", "FRESHWATER JELLYFISH", "FRIGATEBIRD", "FRILLED LIZARD", "FRILLED SHARK", "FROG", "FROGFISH", "FRUIT BAT", "FRUIT FLY", "FUR SEAL",
// LETTER - G
"GABOON VIPER", "GALAPAGOS PENGUIN", "GALAPAGOS SHARK", "GALAPAGOS TORTOISE", "GAR", "GARDEN EEL", "GARGOYLE GECKO", "GARTER SNAKE", "GAZELLE", "GECKO", "GENET", "GENTOO PENGUIN", "GEOFFROYS TAMARIN", "GERBERIAN SHEPSKY", "GERBIL", "GERMAN COCKROACH", "GERMAN PINSCHER", "GERMAN SHEPHERD GUIDE", "GERMAN SHEPPIT", "GERMAN SHEPRADOR", "GERMAN SHORTHAIRED POINTER", "GERMAN SPITZ", "GHARIAL", "GHOST CATFISH", "GHOST CRAB", "GIANT AFRICAN LAND SNAIL", "GIANT ARMADILLO", "GIANT CLAM", "GIANT LEOPARD MOTH", "GIANT PANDA BEAR", "GIANT SALAMANDER", "GIANT SCHNAUZER", "GIANT SCHNOODLE", "GIBBON", "GILA MONSTER", "GIRAFFE", "GLASS FROG", "GLASS LIZARD", "GLECHON", "GLEN OF IMAAL TERRIER", "GLOW WORM", "GNAT", "GOAT", "GOBERIAN", "GOBLIN SHARK", "GOLDADOR", "GOLDEN DOX", "GOLDEN LANCEHEAD", "GOLDEN LION TAMARIN", "GOLDEN MASKED OWL", "GOLDEN NEWFIE", "GOLDEN ORIOLE", "GOLDEN PYRENEES", "GOLDEN RETRIEVER", "GOLDEN SAINT", "GOLDEN SHEPHERD", "GOLDEN-CROWNED FLYING FOX", "GOLDENDOODLE", "GOLDFISH", "GOLIATH FROG", "GOLIATH TIGERFISH", "GOMPHOTHERIUM", "GOONCH CATFISH", "GOOSE", "GOPHER", "GOPHER SNAKE", "GOPHER TORTOISE", "GORDON SETTER", "GORILLA", "GOSHAWK", "GOULDIAN FINCH", "GRASS CARP", "GRASS SNAKE", "GRASSHOPPER", "GRASSHOPPER MOUSE", "GRAY FOX", "GRAY TREE FROG", "GREAT BLUE HERON", "GREAT CRESTED FLYCATCHER", "GREAT DANE", "GREAT DANOODLE", "GREAT EGRET", "GREAT HAMMERHEAD SHARK", "GREAT PLAINS RAT SNAKE", "GREAT PYRENEES", "GREAT WHITE SHARK", "GREATER SWISS MOUNTAIN DOG", "GREEN ANACONDA", "GREEN ANOLE", "GREEN BEE-EATER", "GREEN FROG", "GREEN HERON", "GREEN MAMBA", "GREEN RAT SNAKE", "GREEN SNAKE", "GREEN TREE FROG", "GREEN TREE PYTHON", "GREENLAND DOG", "GREENLAND SHARK", "GREY HERON", "GREY MOUSE LEMUR", "GREY REEF SHARK", "GREY SEAL", "GREYHOUND", "GRIFFON VULTURE", "GRIFFONSHIRE", "GRIZZLY BEAR", "GROENENDAEL", "GROUND SNAKE", "GROUNDHOG (WOODCHUCK)", "GROUPER", "GROUSE", "GUINEA FOWL", "GUINEA PIG", "GUPPY",
// LETTER - H
"HABU SNAKE", "HADDOCK", "HAGFISH", "HALIBUT", "HAMMERHEAD SHARK", "HAMSTER", "HARBOR SEAL", "HARDHEAD CATFISH", "HARE", "HARLEQUIN SNAKE", "HARP SEAL", "HARPY EAGLE", "HARRIER", "HARRIS HAWK", "HAVANESE", "HAVAPOO", "HAVASHIRE", "HAWAIIAN CROW", "HAWAIIAN GOOSE", "HAWAIIAN MONK SEAL", "HAWK MOTH CATERPILLAR", "HEDGEHOG", "HELLBENDER", "HERCULES BEETLE", "HERCULES MOTH", "HERMIT CRAB", "HERON", "HERRING", "HIGHLAND CATTLE", "HIMALAYAN", "HIPPOPOTAMUS", "HOARY BAT", "HOGNOSE SNAKE", "HOKKAIDO", "HONDURAN WHITE BAT", "HONEY BADGER", "HONEY BEE", "HONEY BUZZARD", "HOODED ORIOLE", "HOODED SEAL", "HOOK-NOSED SEA SNAKE", "HOOPOE", "HORGI", "HORN SHARK", "HORNBILL", "HORNED ADDER", "HORNED FROG", "HORNED LIZARD", "HORNED VIPER", "HORSE", "HORSEFLY", "HORSESHOE CRAB", "HOUSE FINCH", "HOUSE SPARROW", "HOUSE WREN", "HOUSEFLY", "HOWLER MONKEY", "HUMAN", "HUMBOLDT PENGUIN", "HUMBOLDT SQUID", "HUMMINGBIRD", "HUMMINGBIRD HAWK-MOTH", "HUMPBACK WHALE", "HUNTAWAY", "HUNTSMAN SPIDER", "HUSKADOR", "HUSKITA", "HUSKY", "HUSKY JACK", "HUSKYDOODLE", "HYAENODON", "HYENA",
// LETTER - I
"IBEX", "IBIS", "IBIZAN HOUND", "ICELANDIC SHEEPDOG", "ICHTHYOSAURUS", "IGUANA", "IMMORTAL JELLYFISH", "IMPALA", "IMPERIAL MOTH", "INDIAN COBRA", "INDIAN ELEPHANT", "INDIAN GIANT SQUIRREL", "INDIAN PALM SQUIRREL", "INDIAN RHINOCEROS", "INDIAN STAR TORTOISE", "INDIANMEAL MOTH", "INDIGO SNAKE", "INDOCHINESE TIGER", "INDRI", "INLAND TAIPAN", "INSECT", "INSECTS", "IRISH DOODLE", "IRISH SETTER", "IRISH TERRIER", "IRISH WATER SPANIEL", "IRISH WOLFHOUND", "ITALIAN GREYHOUND", "IVORY-BILLED WOODPECKER",
// LETTER - J
"JACANA", "JACK RUSSELL", "JACKABEE", "JACKAL", "JACKDAW", "JACKRABBIT", "JACKSON’S CHAMELEON", "JAGUAR", "JAGUARUNDI CAT", "JAMAICAN BOA", "JAPANESE BEETLE", "JAPANESE CHIN", "JAPANESE MACAQUE", "JAPANESE RAT SNAKE", "JAPANESE SPITZ", "JAPANESE SQUIRREL", "JAPANESE TERRIER", "JAVAN RHINOCEROS", "JAVANESE", "JELLYFISH", "JERBOA", "JONAH CRAB", "JORO SPIDER", "JUMPING SPIDER", "JUNGLE CARPET PYTHON", "JUNGLEFOWL",
// LETTER - K
"KAI KEN", "KAKAPO", "KANGAL", "KANGAROO", "KANGAROO RAT", "KEEL-BILLED TOUCAN", "KEELBACK", "KEESHOND", "KENYAN SAND BOA", "KERRY BLUE TERRIER", "KESTREL", "KETA SALMON", "KEY DEER", "KIKO GOAT", "KILLDEER", "KILLER WHALE", "KINABALU GIANT RED LEECH", "KINDER GOAT", "KING COBRA", "KING CRAB", "KING PENGUIN", "KING RAT SNAKE", "KING SHEPHERD", "KING SNAKE", "KING VULTURE", "KINGFISHER", "KINKAJOU", "KIRTLAND’S SNAKE", "KISHU", "KIT FOX", "KITEFIN SHARK", "KIWI", "KLIPSPRINGER", "KOALA", "KODKOD", "KOI FISH", "KOMODO DRAGON", "KOOIKERHONDJE", "KOOKABURRA", "KOOLIE", "KORI BUSTARD", "KRAIT", "KRILL", "KUDU", "KUVASZ",
// LETTER - L
"LABAHOULA", "LABMARANER", "LABRADANE", "LABRADOODLE", "LABRADOR RETRIEVER", "LABRAHEELER", "LADYBUG", "LAKE STURGEON", "LAKELAND TERRIER", "LAMANCHA GOAT", "LAMPREY", "LANCASHIRE HEELER", "LAPPET-FACED VULTURE", "LAPPONIAN HERDER", "LAWNMOWER BLENNY", "LAZARUS LIZARD", "LEAF-TAILED GECKO", "LEATHERBACK SEA TURTLE", "LEECH", "LEMMING", "LEMUR", "LEONBERGER", "LEOPARD", "LEOPARD CAT", "LEOPARD FROG", "LEOPARD GECKO", "LEOPARD LIZARD", "LEOPARD SEAL", "LEOPARD SHARK", "LEOPARD TORTOISE", "LHASA APSO", "LHASAPOO", "LIGER", "LION", "LION’S MANE JELLYFISH", "LIONFISH", "LITTLE BROWN BAT", "LITTLE PENGUIN", "LIVYATAN", "LIZARD", "LIZARDFISH", "LLAMA", "LOACH", "LOBSTER", "LOCUST", "LONE STAR TICK", "LONG-EARED OWL", "LONG-HAIRED ROTTWEILER", "LONG-TAILED TIT", "LONGFIN MAKO SHARK", "LONGNOSE GAR", "LORIKEET", "LOWCHEN", "LUMPFISH", "LUNGFISH", "LYNX", "LYREBIRD",
// LETTER - M
"MACAQUE", "MACARONI PENGUIN", "MACAW", "MACKENZIE WOLF", "MADAGASCAR HISSING COCKROACH", "MADAGASCAR TREE BOA", "MAGELLANIC PENGUIN", "MAGGOT", "MAGPIE", "MAHI MAHI (DOLPHIN FISH)", "MAIASAURA", "MAINE COON", "MALAYAN CIVET", "MALAYAN KRAIT", "MALAYAN TIGER", "MALCHI", "MALLARD", "MALTEAGLE", "MALTESE", "MALTESE SHIH TZU", "MALTIPOO", "MAMBA", "MAMUSHI SNAKE", "MAN OF WAR JELLYFISH", "MANATEE", "MANCHESTER TERRIER", "MANDARIN RAT SNAKE", "MANDRILL", "MANED WOLF", "MANGROVE SNAKE", "MANTA RAY", "MANTELLA FROG", "MARABOU STORK", "MARBLE FOX", "MARINE IGUANA", "MARINE TOAD", "MARKHOR", "MARMOSET", "MARMOT", "MARSH FROG", "MASKED ANGELFISH", "MASKED PALM CIVET", "MASSASAUGA", "MASTADOR", "MASTIFF", "MAYFLY", "MEAGLE", "MEALYBUG", "MEERKAT", "MEGALANIA", "MEGALODON", "MEGAMOUTH SHARK", "MEGATHERIUM", "MEKONG GIANT CATFISH", "MEXICAN ALLIGATOR LIZARD", "MEXICAN BLACK KINGSNAKE", "MEXICAN EAGLE (NORTHERN CRESTED CARACARA)", "MEXICAN FREE-TAILED BAT", "MEXICAN MOLE LIZARD", "MICRORAPTOR", "MIDGET FADED RATTLESNAKE", "MIKI", "MILK SNAKE", "MILKFISH", "MILLIPEDE", "MINI LABRADOODLE", "MINIATURE BULL TERRIER", "MINIATURE HUSKY", "MINIATURE PINSCHER", "MINK", "MINKE WHALE", "MISSISSIPPI KITE", "MOCCASIN SNAKE", "MOJARRA", "MOJAVE RATTLESNAKE", "MOLA MOLA (OCEAN SUNFISH)", "MOLE", "MOLE CRICKET", "MOLE SNAKE", "MOLLY", "MONARCH BUTTERFLY", "MONGOOSE", "MONGREL", "MONITOR LIZARD", "MONKEY", "MONKFISH", "MONOCLED COBRA", "MONTE IBERIA ELEUTH", "MOON JELLYFISH", "MOORHEN", "MOOSE", "MORAY EEL", "MORKIE", "MOSASAURUS", "MOSCOW WATCHDOG", "MOSQUITO", "MOTH", "MOUNTAIN BLUEBIRD", "MOUNTAIN CUR", "MOUNTAIN FEIST", "MOUNTAIN GORILLA", "MOUNTAIN LION", "MOURNING DOVE", "MOUSE", "MOZAMBIQUE SPITTING COBRA", "MUD SNAKE", "MUDI", "MUDPUPPY", "MULE", "MULGA SNAKE", "MUNTJAC", "MUSKOX", "MUSKRAT", "MUSSURANA SNAKE", "MUTTABURRASAURUS", "MYNA BIRD",
// LETTER - N
"NAKED MOLE RAT", "NARWHAL", "NATTERJACK", "NEANDERTHAL", "NEAPOLITAN MASTIFF", "NEBELUNG", "NEEDLEFISH", "NEON TETRA", "NEPTUNE GROUPER", "NEWFOUNDLAND", "NEWFYPOO", "NEWT", "NICOBAR PIGEON", "NIGERIAN GOAT", "NIGHT ADDER", "NIGHT HERON", "NIGHT SNAKE", "NIGHTINGALE", "NILE CROCODILE", "NILGAI", "NO SEE UMS", "NORFOLK TERRIER", "NORTH AMERICAN BLACK BEAR", "NORTHERN ALLIGATOR LIZARD", "NORTHERN CARDINAL", "NORTHERN FUR SEAL", "NORTHERN INUIT DOG", "NORTHERN WATER SNAKE", "NORWEGIAN BUHUND", "NORWEGIAN ELKHOUND", "NORWEGIAN FOREST", "NORWEGIAN LUNDEHUND", "NORWICH TERRIER", "NOSE-HORNED VIPER", "NOVA SCOTIA DUCK TOLLING RETRIEVER", "NUBIAN GOAT", "NUDIBRANCH", "NUMBAT", "NURSE SHARK", "NYALA",
// LETTER - O
"OAK TOAD", "OCEANIC WHITETIP SHARK", "OCELOT", "OCTOPUS", "OENPELLI PYTHON", "OKAPI", "OLD ENGLISH SHEEPDOG", "OLIVE BABOON", "OLIVE SEA SNAKE", "OLM", "OPOSSUM", "ORANG-UTAN", "ORANGE-CROWNED WARBLER", "ORB WEAVER", "ORNITHOMIMUS", "ORTOLAN BUNTING", "OSCAR FISH", "OSTRICH", "OTTER", "OTTERHOUND", "OVIRAPTOR", "OWL", "OX", "OYSTER", "OYSTER TOADFISH",
// LETTER - P
"PACIFIC SLEEPER SHARK", "PADDLEFISH", "PADEMELON", "PAINTED TURTLE", "PANGOLIN", "PANTHER", "PAPILLON", "PARADISE FLYING SNAKE", "PARAKEET", "PARASAUROLOPHUS", "PARROT", "PARROT SNAKE", "PARROTFISH", "PARROTLET", "PARSON RUSSELL TERRIER", "PATAGOTITAN", "PATAS MONKEY", "PATTERDALE TERRIER", "PEACOCK", "PEACOCK BUTTERFLY", "PEACOCK SPIDER", "PEAGLE", "PEEKAPOO", "PEKINGESE", "PELICAN", "PEMBROKE WELSH CORGI", "PENGUIN", "PENNSYLVANIA WOOD COCKROACH", "PEPPERED MOTH", "PEPPERMINT ANGELFISH", "PERE DAVIDS DEER", "PEREGRINE FALCON", "PERINGUEY’S ADDER", "PERRO DE PRESA CANARIO", "PERSIAN", "PERUVIAN INCA ORCHID", "PESQUET’S PARROT (DRACULA PARROT)", "PETIT BASSET GRIFFON VENDÉEN", "PETITE GOLDENDOODLE", "PHEASANT", "PHILIPPINE COBRA", "PHORUSRHACOS", "PIED BALL PYTHON", "PIED TAMARIN", "PIG", "PIGEON", "PIKA", "PIKE FISH", "PILEATED WOODPECKER", "PINE MARTEN", "PINE SNAKE", "PINE SNAKE", "PINK FAIRY ARMADILLO", "PIPE SNAKE", "PIPEFISH", "PIRANHA", "PIT BULL", "PITADOR", "PITSKY", "PLAINS HOGNOSE SNAKE", "PLATINUM AROWANA", "PLATYBELODON", "PLATYPUS", "POCKET BEAGLE", "POCKET PITBULL", "POINTER", "POISON DART FROG", "POLAR BEAR", "POLECAT", "POLISH LOWLAND SHEEPDOG", "POLKA DOT STINGRAY", "POLYPHEMUS MOTH", "POMAPOO", "POMCHI", "POMEAGLE", "POMERANIAN", "POMSKY", "POND SKATER", "POOCHON", "POODLE", "POOGLE", "POOL FROG", "PORBEAGLE SHARK", "PORCUPINE", "PORPOISE", "POSSUM", "POTOO", "POTOROO", "PRAIRIE DOG", "PRAIRIE RATTLESNAKE", "PRAWN", "PRAYING MANTIS", "PROBOSCIS MONKEY", "PROCOPTODON", "PRONGHORN", "PSITTACOSAURUS", "PTERANODON", "PTERODACTYL", "PUDELPOINTER", "PUFF ADDER", "PUFFERFISH", "PUFFIN", "PUG", "PUGAPOO", "PUGGLE", "PUGSHIRE", "PUMA", "PUMI", "PURPLE EMPEROR BUTTERFLY", "PURPLE FINCH", "PUSS MOTH", "PYGMY HIPPOPOTAMUS", "PYGMY MARMOSET (FINGER MONKEY)", "PYGMY PYTHON", "PYGMY SHARK", "PYGORA GOAT", "PYJAMA SHARK", "PYRADOR", "PYREDOODLE", "PYTHON",
// LETTER - Q
"QUAGGA", "QUAIL", "QUEEN SNAKE", "QUETZAL", "QUOKKA", "QUOLL",
// LETTER - R
"RABBIT", "RACCOON", "RACCOON DOG", "RACER SNAKE", "RADIATED TORTOISE", "RAGAMUFFIN", "RAGDOLL", "RAGGLE", "RAINBOW BOA", "RAINBOW SHARK", "RAT", "RAT SNAKES", "RAT TERRIER", "RATTLESNAKE", "RED DIAMONDBACK RATTLESNAKE", "RED FINCH", "RED FOX", "RED KITE", "RED KNEE TARANTULA", "RED PANDA", "RED RACER SNAKE", "RED SPITTING COBRA", "RED SQUIRREL", "RED TAIL BOA (COMMON BOA)", "RED WOLF", "RED-BELLIED BLACK SNAKE", "RED-BILLED QUELEA BIRD", "RED-EARED SLIDER", "RED-EYED TREE FROG", "RED-FOOTED TORTOISE", "RED-HANDED TAMARIN", "RED-HEADED VULTURE", "RED-LIPPED BATFISH", "RED-WINGED BLACKBIRD", "REDBACK SPIDER", "REDBONE COONHOUND", "REDTAIL CATFISH", "REEF SHARK", "REINDEER", "REPENOMAMUS", "RETICULATED PYTHON", "RHINO VIPER", "RHINOCEROS", "RHOMBIC EGG-EATER SNAKE", "RIBBON EEL", "RIBBON SNAKE", "RING-BILLED GULL", "RINGED KINGFISHER", "RINKHALS SNAKE", "RIVER OTTER", "RIVER TURTLE", "ROBIN", "ROCK CRAB", "ROCK HYRAX", "ROCK PYTHON", "ROCKFISH", "ROCKHOPPER PENGUIN", "RODENTS", "ROE DEER", "ROOSTER", "ROSE-BREASTED GROSBEAK", "ROSEATE SPOONBILL", "ROSY BOA", "ROTTSKY", "ROTTWEILER", "ROUGH GREEN SNAKE", "ROYAL PENGUIN", "RUBBER BOA", "RUBY-THROATED HUMMINGBIRD", "RUDDY TURNSTONE", "RUSSEL'S VIPER", "RUSSELL TERRIER", "RUSSIAN BEAR DOG", "RUSSIAN BLUE", "RUSSIAN TORTOISE",
// LETTER - S
"SAANEN GOAT","SAARLOOS WOLFDOG","SABER-TOOTHED TIGER","SABLE","SABLE BLACK GERMAN SHEPHERD","SABLE FERRET","SAIGA","SAINT BERDOODLE","SAINT BERNARD","SAINT SHEPHERD","SALAMANDER",
"SALMON","SALMON SHARK","SALUKI","SAMBAR","SAMOYED","SAN FRANCISCO GARTER SNAKE","SAND CRAB",
"SAND LIZARD","SAND TIGER SHARK","SAND VIPER","SAOLA","SARDINES","SATANIC LEAF-TAILED GECKO","SAUROPODA", "SAVANNA GOAT","SAVANNAH SPARROW", "SAW-SCALED VIPER","SAWFISH","SCARLET KINGSNAKE",
"SCARLET MACAW","SCHIPPERKE","SCHNEAGLE","SCHNOODLE","SCIMITAR-HORNED ORYX", 
"SCORPION", "SCORPION FISH", "SCOTTISH TERRIER", "SCROTUM FROG", "SCULPIN", "SEA ANEMONE", "SEA DRAGON", "SEA EAGLE", "SEA LION", "SEA OTTER", "SEA ROACH", "SEA SLUG", "SEA SQUIRT", "SEA TURTLE", "SEA URCHIN", "SEAGULL", "SEAHORSE", "SEAL", "SEALYHAM TERRIER", "SEI WHALE", "SENEGAL PARROT", "SERVAL", "SHARK", "SHARP-TAILED SNAKE", "SHEEP", "SHEEPADOODLE", "SHEPADOODLE", "SHEPKITA", "SHEPWEILER", "SHIBA INU", "SHIH POO", "SHIH TZU", "SHOEBILL STORK", "SHOLLIE", "SHORT-FACED BEAR", "SHORTFIN MAKO SHARK", "SHREW", "SHRIMP", "SIAMESE", "SIBERIAN", "SIBERIAN HUSKY", "SIBERIAN IBEX", "SIBERIAN RETRIEVER", "SIBERIAN TIGER", "SIBERPOO", "SIDEWINDER", "SILKIE CHICKEN", "SILKY SHARK", "SILKY TERRIER", "SILVER DOLLAR", "SILVER LABRADOR", "SINOSAUROPTERYX", "SIXGILL SHARK", "SKATE FISH", "SKINK LIZARD", "SKIPJACK TUNA", "SKUNK", "SKYE TERRIER", "SLEEPER SHARK", "SLOTH", "SLOW WORM", "SLUG", "SMOKYBROWN COCKROACH", "SMOOTH FOX TERRIER", "SMOOTH GREEN SNAKE", "SMOOTH SNAKE", "SNAIL", "SNAKE", "SNAPPING TURTLE", "SNOOK FISH", "SNORKIE", "SNOUTED COBRA", "SNOW CRAB", "SNOW LEOPARD", "SNOWSHOE", "SNOWSHOE HARE", "SNOWY OWL", "SOCKEYE SALMON", "SOMALI", "SONG SPARROW", "SONG THRUSH", "SOUTH CHINA TIGER", "SOUTHERN BLACK RACER", "SOUTHERN HOGNOSE SNAKE", "SOUTHERN PACIFIC RATTLESNAKE", "SPADEFOOT TOAD", "SPANADOR", "SPANISH GOAT", "SPANISH MASTIFF", "SPARROW", "SPARROWHAWK", "SPECKLED KINGSNAKE", "SPECTACLED BEAR", "SPERM WHALE", "SPHYNX TRAITS: WHAT TO KNOW BEFORE YOU BUY", "SPIDER", "SPIDER BALL PYTHON", "SPIDER MONKEY", "SPIDER WASP", "SPIDER-TAILED HORNED VIPER", "SPINNER SHARK", "SPINONE ITALIANO", "SPINOSAURUS", "SPINY DOGFISH", "SPINY HILL TURTLE", "SPITTING COBRA", "SPIXS MACAW", "SPONGE", "SPOTTED GAR", "SPOTTED LANTERNFLY", "SPOTTED PYTHON", "SPRINGADOR", "SPRINGBOK", "SPRINGERDOODLE", "SQUASH BEETLE", "SQUID", "SQUIRREL", "SQUIRREL MONKEY", "SQUIRRELFISH", "SRI LANKAN ELEPHANT", "STABYHOUN", "STAFFORDSHIRE BULL TERRIER", "STAG BEETLE", "STANDARD SCHNAUZER", "STAR-NOSED MOLE", "STARFISH", "STARGAZER FISH", "STEELHEAD SALMON", "STELLER'S SEA COW", "STICK INSECT", "STILETTO SNAKE", "STINGRAY", "STOAT", "STONE CRAB", "STORK", "STRIPED HYENA", "STRIPED ROCKET FROG", "STURGEON", "STYRACOSAURUS", "SUCHOMIMUS", "SUCKER FISH", "SUGAR GLIDER", "SULCATA TORTOISE", "SUMATRAN ELEPHANT", "SUMATRAN ORANG-UTAN", "SUMATRAN RHINOCEROS", "SUMATRAN TIGER", "SUN BEAR", "SUNBEAM SNAKE", "SURGEONFISH", "SWAI FISH", "SWAN", "SWEDISH VALLHUND", "SYRIAN HAMSTER",
// LETTER - T
"TACO TERRIER", "TAIPAN", "TAKIN", "TAMASKAN", "TANG", "TAPANULI ORANG-UTAN", "TAPIR", "TARANTULA HAWK", "TARBOSAURUS", "TARPON", "TARSIER", "TASMANIAN DEVIL", "TASMANIAN TIGER", "TAWNY OWL", "TEDDY BEAR HAMSTER", "TEDDY ROOSEVELT TERRIER", "TELESCOPE FISH", "TENNESSEE WALKING HORSE", "TENTERFIELD TERRIER", "TERMITE", "TERRIER", "TERROR BIRD", "TETRA", "TEXAS BLIND SNAKE", "TEXAS CORAL SNAKE", "TEXAS GARTER SNAKE", "TEXAS HEELER", "TEXAS INDIGO SNAKE", "TEXAS NIGHT SNAKE", "TEXAS RAT SNAKE", "TEXAS SPINY LIZARD", "THAI RIDGEBACK", "THORNY DEVIL", "THRESHER SHARK", "THRUSH", "THYLACOLEO", "TIBETAN FOX", "TIBETAN MASTIFF", "TIBETAN SPANIEL", "TIBETAN TERRIER", "TICK", "TIFFANY", "TIGER", "TIGER BEETLE", "TIGER MOTH", "TIGER RATTLESNAKE", "TIGER SALAMANDER", "TIGER SHARK", "TIMBER RATTLESNAKE (CANEBRAKE RATTLESNAKE)", "TIRE TRACK EEL", "TITANOBOA", "TOADFISH", "TORKIE", "TORTOISE", "TOUCAN", "TOY FOX TERRIER", "TOY POODLE", "TRANSYLVANIAN HOUND", "TREE FROG", "TREE KANGAROO", "TREE SNAKE", "TREE SWALLOW", "TREECREEPER", "TREEING TENNESSEE BRINDLE", "TREEING WALKER COONHOUND", "TROODON", "TROPICBIRD", "TROUT", "TSETSE FLY", "TUATARA", "TUNA", "TURKEY", "TURKISH ANGORA", "TURTLES", "TWIG SNAKE", "TYRANNOSAURUS REX",
// LETTER - U
"UAKARI", "UGUISU", "UINTA GROUND SQUIRREL", "UINTATHERIUM", "UMBRELLABIRD", "UNAU (LINNAEUS’S TWO-TOED SLOTH)", "URAL OWL", "URUTU SNAKE", "UTONAGAN",
// LETTER - V
"VAMPIRE BAT", "VAMPIRE SQUID", "VAQUITA", "VELOCIRAPTOR", "VENUS FLYTRAP", "VERVET MONKEY", "VICUÑA", "VINE SNAKE", "VINEGAROON", "VIPER", "VIPER SHARK (DOGFISH)", "VIRGIN ISLANDS DWARF GECKO", "VIZSLA", "VOLPINO ITALIANO", "VULTURE",
// LETTER - W
"WAHOO FISH", "WALKING CATFISH", "WALLABY", "WALLEYE FISH", "WALRUS", "WANDERING ALBATROSS", "WARTHOG", "WASP", "WATER BUFFALO", "WATER DRAGON", "WATER VOLE", "WEASEL", "WEAVER BIRD", "WEIMARANER", "WEIMARDOODLE", "WELS CATFISH", "WELSH CORGI", "WELSH TERRIER", "WEST HIGHLAND TERRIER", "WESTERN BLIND SNAKE", "WESTERN DIAMONDBACK RATTLESNAKE", "WESTERN GORILLA", "WESTERN GREEN MAMBA", "WESTERN HOGNOSE SNAKE", "WESTERN LOWLAND GORILLA", "WESTERN RAT SNAKE", "WESTIEPOO", "WHALE SHARK", "WHEATEN TERRIER", "WHIMBREL", "WHINCHAT", "WHIPPET", "WHIPTAIL LIZARD", "WHITE BUTTERFLY", "WHITE FERRET / ALBINO FERRETS", "WHITE RHINOCEROS", "WHITE SHARK", "WHITE TIGER", "WHITE-FACED CAPUCHIN", "WHITE-TAIL DEER", "WHITE-TAILED EAGLE", "WHITING", "WHOODLE", "WHOOPING CRANE", "WILD BOAR", "WILDEBEEST", "WILLOW WARBLER", "WIRE FOX TERRIER", "WIREHAIRED POINTING GRIFFON", "WOLF", "WOLF EEL", "WOLF SNAKE", "WOLF SPIDER", "WOLFFISH", "WOLVERINE", "WOMA PYTHON", "WOMBAT", "WOOD BISON", "WOOD FROG", "WOOD TICK", "WOOD TURTLE", "WOODLOUSE", "WOODLOUSE SPIDER", "WOODPECKER", "WOODRAT", "WOOLLY MAMMOTH", "WOOLLY MONKEY", "WOOLLY RHINOCEROS", "WORM", "WORM SNAKE", "WRASSE", "WRITING SPIDER", "WROUGHT IRON BUTTERFLYFISH", "WYOMING TOAD",
// LETTER - X
"X-RAY TETRA", "XERUS", "XOLOITZCUINTLI",
// LETTER - Y
"YAK", "YAKUTIAN LAIKA", "YARARA", "YELLOW ANACONDA", "YELLOW COBRA", "YELLOW SAC SPIDER", "YELLOW SPOTTED LIZARD", "YELLOW-BELLIED SEA SNAKE", "YELLOW-EYED PENGUIN", "YELLOWFIN TUNA", "YETI CRAB", "YORANIAN", "YORKIE BICHON", "YORKIE-POO", "YORKSHIRE TERRIER",
// LETTER - Z
"ZEBRA", "ZEBRA FINCH", "ZEBRA MUSSELS", "ZEBRA PLECO", "ZEBRA SHARK", "ZEBRA SNAKE", "ZEBRA SPITTING COBRA", "ZEBU", "ZONKEY", "ZORSE", "ZUCHON",
]
//----------------------------------------------------------------------//
// DB -  STATES - ENGLISH
//----------------------------------------------------------------------//
const stateCategory = [
// LETTER - A
"ALABAMA","ALASKA","ARIZONA","ARKANSAS",
// LETTER - B
// LETTER - C
"CALIFORNIA","COLORADO","CONNECTICUT",
// LETTER - D
"DELAWARE",
// LETTER - F
"FLORIDA",
// LETTER - G
"GEORGIA",
// LETTER - H
"HAWAII",
// LETTER - I
"IDAHO","ILLINOIS","INDIANA","IOWA",
// LETTER - J
// LETTER - K
"KANSAS","KENTUCKY",
// LETTER - L
"LOUISIANA",
// LETTER - M
"MAINE","MARYLAND","MASSACHUSETTS","MICHIGAN","MINNESOTA","MISSISSIPPI","MISSOURI","MONTANA",
// LETTER - N
"NEBRASKA","NEVADA","NEW HAMPSHIRE","NEW JERSEY","NEW MEXICO","NEW YORK","NORTH CAROLINA","NORTH DAKOTA",
// LETTER - O
"OHIO","OKLAHOMA","OREGON",
// LETTER - P
"PENNSYLVANIA",
// LETTER - Q
// LETTER - R
"RHODE ISLAND",
// LETTER - S
"SOUTH CAROLINA","SOUTH DAKOTA",
// LETTER - T
"TENNESSEE","TEXAS",
// LETTER - U
"UTAH",
// LETTER - V
"VERMONT","VIRGINIA",
// LETTER - W
"WASHINGTON","WEST VIRGINIA","WISCONSIN","WYOMING"
// LETTER - X
// LETTER - Y
// LETTER - Z
]
//----------------------------------------------------------------------//
// DB -  COLORS - ENGLISH
//----------------------------------------------------------------------//
const colorCategory = [// LETTER - A
"ALABASTER","ALICE BLUE","ALIZARIN CRIMSON","ALMOND","AMARANTH","AMARANTHINE","AMBER","AMETHYST","ANTIQUE BRASS","ANTIQUE WHITE","APPLE GREEN","APRICOT","AQUA","AQUAMARINE","ARGENT","ARTICHOKE","ASH","ASH GRAY","ASPARAGUS","AUBERGINE","AUBURN","AVOCADO","AZURE",
// LETTER -B
"BABY BLUE","BABY PINK","BANANA","BATTLESHIP GREY","BAY","BEAVER","BEIGE","BERMUDA GREEN","BERYL","BICE","BICE BLUE","BICE GREEN","BISCUIT","BISQUE","BLACK","BLANCHED ALMOND","BLAZE ORANGE","BLONDE","BLOOD RED","BLUE","BLUEBERRY","BLUE GREEN","BLUE VIOLET","BONE","BOTTLE GREEN","BRASS","BRICK RED","BRONZE","BRONZE YELLOW","BROWN","BUCKSKIN","BUFF","BURGUNDY","BURLYWOOD","BURNT ORANGE","BURNT SIENNA","BURNT UMBER","BUTTERSCOTCH",
//LETTER - C
"CADET BLUE","CAMBRIDGE BLUE","CAMEL","CANARY","CANTALOUPE","CAPPUCCINO","CARAMEL","CARDINAL","CARMINE","CARNATION","CARNELIAN","CARROT","CELADON","CERISE","CERULEAN","CHAMOIS","CHAMPAGNE","CHARCOAL","CHARTREUSE","CHERRY RED","CHESTNUT","CHINESE RED","CHOCOLATE","CINEREOUS","CINNABAR","CINNAMON","CITRINE","CLAIR DE LUNE","CLARET","COAL BLACK","COBALT BLUE","COCOA","COFFEE","COOL GREY","COPENHAGEN BLUE","COPPER","COQUELICOT","CORAL","CORNFLOWER","CORNFLOWER BLUE","CORNSILK","CRANBERRY","CREAM","CRIMSON","CUPREOUS","CYAN", 
//LETTER - D
"DAFFODIL","DAMASK","DANDELION","DESERT SAND","DODGER BLUE","DOVE GREY","DRAB","DUCK-EGG BLUE","DUN",
//LETTER - E
"EAU DE NIL","EBONY","ECRU","EGGSHELL","EGGSHELL BLUE","ELECTRIC-BLUE","EMERALD","EMERALD GREEN","EUCALYPTUS",
//LETTER - F
"FAWN","FEDERAL YELLOW","FIRE BRICK","FIRE ENGINE RED","FLAME","FLAMINGO","FLAXEN","FLESH","FLORAL WHITE","FOREST GREEN","FROST","FUCHSIA","FUSCOUS",
//LETTER - G
"GAINSBORO","GAMBOGE","GARNET","GENTIAN BLUE","GENTIAN VIOLET","GERANIUM","GINGER","GLAUCOUS","GOLD","GOLDEN BROWN","GOLDENROD","GOLD OCHRE","GRAPE","GRASS-GREEN","GREEN","GREEN","GREY","GRIZZLE","GULES","GUNMETAL GREY", 
// LETTER -H
"HARLEQUIN","HARVEST GOLD","HAZEL","HEATHER","HELIOTROPE","HENNA","HEPATIC","HOAR","HONEY","HONEYDEW","HOT PINK","HUNTER GREEN",
//LETTER - I
"ICE BLUE","INCARNADINE","INDIAN RED","INDIGO","INTERNATIONAL ORANGE","IRON GREY","IVORY",
//LETTER - J
"JADE","JADE GREEN","JET","JONQUIL","JUNGLE GREEN",
//LETTER - K
"KELLY GREEN","KENDAL GREEN","KHAKI","KHAKI GREEN",
//LETTER - L
"LAPIS LAZULI","LAUREL GREEN","LAVA","LAVENDER","LEMON","LEMON CHIFFON","LICORICE","LILAC","LIME","LINCOLN GREEN","LINEN","LION","LIVER","LODEN","LOVAT", 
//LETTER - M
"MACARONI-AND-CHEESE","MADDER","MAGENTA","MAGIC MINT","MAGNOLIA","MAHOGANY","MALACHITE","MANATEE","MANGO","MANTIS","MAROON","MAUVE","MAZARINE","MELON","MIDNIGHT BLUE","MIGNONETTE","MILITARY GREY","MINT","MINT CREAM","MISTY ROSE","MOCCASIN","MOCHA","MOSS GREEN","MULBERRY","MUMMY BROWN","MUSTARD","MYRTLE", 
//LETTER - N
"NATURAL","NAVAJO WHITE","NAVY","NILE BLUE","NILE GREEN",
//LETTER - O
"OAK","OATMEAL","OCEAN GREY","OCHRE","OFF-WHITE","OLD GOLD","OLD LACE","OLIVE","OLIVE DRAB","ONYX","ORANGE","ORCHID","OUTER SPACE","OXBLOOD","OXFORD BLUE","OYSTER", 
//LETTER - P
"PANSY","PAPRIKA","PARIS GREEN","PATINA","PEACH","PEACOCK BLUE","PEA GREEN","PEAR","PEARL GREY","PEARLY","PERIWINKLE","PERSE","PETROL BLUE","PETUNIA","PEWTER","PICEOUS","PILLAR-BOX RED","PINEAPPLE","PINE GREEN","PINK","PISTACHIO GREEN","PLATINUM","PLATINUM BLOND","PLUM","POMEGRANATE","POMPEIAN RED","POPPY","POWDER BLUE","PRIMROSE","PRUSSIAN BLUE","PUCE","PUKE","PURPLE","PURPURE", 
//LETTER - Q
"QUARTZ","QUINCE",
//LETTER - R
"RASPBERRY","RAW SIENNA","RED","RED VIOLET","RESEDA","RIFLE GREEN","ROBIN'S-EGG BLUE","ROSE","ROUGE","ROYAL BLUE","ROYAL PURPLE","RUBY","RUSSET","RUST", 
//LETTER - S
"SABLE","SADDLE BROWN","SAFETY ORANGE","SAFFRON","SAGE GREEN","SALMON","SAND","SANDY","SANGRIA","SANGUINE","SAPPHIRE","SARD","SAXE BLUE","SCARLET","SCHOOL BUS YELLOW","SEA GREEN","SEASHELL","SEPIA","SHADOW","SHOCKING PINK","SIENNA","SILVERVSILVER-GREY","SKY BLUE","SLATE","SLATE BLACK","SLATE BLUE","SLATE GREY","SMARAGDINE","SMOKE","SNOW","SORREL","SPRING GREEN","STAMMEL","STEEL BLUE","STONE","STRAW","STRAWBERRY","SULFUR","SUNFLOWER","SUNSET","SUNSET ORANGE", 
//LETTER - T
"TAN","TANGERINE","TAUPE","TAXI YELLOW","TEAK","TEAL","TERRACOTTA","TIMBERWOLF","TITIAN","TOPAZ","TOW-COLORED","TURKEY RED","TURQUOISE","TYRIAN PURPLE", 
//LETTER - U
"ULTRAMARINE","UMBER",
//LETTER - V
"VANDYKE BROWN","VENETIAN RED","VERDANT","VERDIGRIS","VERMILION","VERT","VIOLET","VIOLET RED","VIRID","VIRIDIAN",
//LETTER - W
"WALNUT","WATERMELON","WEDGWOOD BLUE","WHEAT","WHEATEN","WHITE","WINE",
//LETTER - X
"XANTHIC",
//LETTER - Y
"YELLOW",
//LETTER - Z
"ZAFFRE","ZOMP"]

//----------------------------------------------------------------------//
// DB -  COUNTRIES - ENGLISH
//----------------------------------------------------------------------//
const countryCategory = [
// LETTER - A
"AFGHANISTAN","ALBANIA","ALGERIA","ANDORRA","ANGOLA","ANTIGUA AND BARBUDA","ARGENTINA","ARMENIA","AUSTRALIA","AUSTRIA","AZERBAIJAN",
 //LETTER - B
"BAHAMAS","BAHRAIN","BANGLADESH","BARBADOS","BELARUS","BELGIUM", "BELIZE", "BENIN","BHUTAN","BOLIVIA","BOSNIA AND HERZEGOVINA","BOTSWANA","BRAZIL","BRUNEI","BULGARIA","BURKINA FASO","BURUNDI",
// LETTER - C
 "CABO VERDE","CAMBODIA","CAMEROON","CANADA","CENTRAL AFRICAN REPUBLIC","CAR","CHAD","CHILE","CHINA","COLOMBIA","COMOROS","CONGO, DEMOCRATIC REPUBLIC OF THE","CONGO, REPUBLIC OF THE","COSTA RICA","COTE D'IVOIRE","CROATIA","CUBA","CYPRUS","CZECHIA",
// LETTER - D
"DENMARK","DJIBOUTI","DOMINICA","DOMINICAN REPUBLIC",
// LETTER - E
 "ECUADOR","EGYPT","EL SALVADOR","EQUATORIAL GUINEA","ERITREA","ESTONIA","ESWATINI","ETHIOPIA",
// LETTER - F
"FIJI","FINLAND","FRANCE",
// LETTER - G
"GABON","GAMBIA","GEORGIA","GERMANY","GHANA","GREECE","GRENADA","GUATEMALA","GUINEA","GUINEA-BISSAU","GUYANA",
// LETTER - H
"HAITI","HONDURAS","HUNGARY",
// LETTER - I
"ICELAND","INDIA","INDONESIA","IRAN","IRAQ","IRELAND","ISRAEL","ITALY",
// LETTER - J
"JAMAICA","JAPAN","JORDAN",
// LETTER - K
"KAZAKHSTAN","KENYA","KIRIBATI","KOSOVO","KUWAIT","KYRGYZSTAN",
// LETTER - L
"LAOS","LATVIA","LEBANON","LESOTHO","LIBERIA","LIBYA","LIECHTENSTEIN","LITHUANIA","LUXEMBOURG",
// LETTER - M
"MADAGASCAR","MALAWI","MALAYSIA","MALDIVES","MALI","MALTA","MARSHALL ISLANDS","MAURITIUS","MEXICO","MICRONESIA","MOLDOVA","MONACO","MONGOLIA","MONTENEGRO","MOROCCO","MOZAMBIQUE",
// LETTER - N
"NAMIBIA","NAURU","NEPAL","NETHERLANDS", "NEW ZEALAND", "NICARAGUA","NIGER","NIGERIA","NORTH KOREA","NORTH MACEDONIA", "NORWAY",
// LETTER - O
"OMAN",
// LETTER - P
"PAKISTAN","PALAU","PALESTINE","PANAMA","PAPUA NEW GUINEA","PARAGUAY","PERU","PHILIPPINES","POLAND","PORTUGAL",
// LETTER - Q
"QATAR",
// LETTER - R
"ROMANIA","RUSSIA","RWANDA",
// LETTER - S
"SAINT KITTS AND NEVIS","SAINT LUCIA","SAINT VINCENT AND THE GRENADINES","SAMOA","SAN MARINO","SAO TOME AND PRINCIPE","SAUDI ARABIA","SENEGAL","SERBIA","SEYCHELLES","SIERRA LEONE","SINGAPORE","SLOVAKIA","SLOVENIA","SOLOMON ISLANDS","SOMALIA","SOUTH AFRICA","SOUTH KOREA","SOUTH SUDAN","SPAIN","SRI LANKA", "SUDAN","SURINAME","SWEDEN","SWITZERLAND","SYRIA",
// LETTER - T
"TAIWAN","TAJIKISTAN","TANZANIA","THAILAND","TIMOR-LESTE","TOGO","TONGA","TRINIDAD AND TOBAGO","TUNISIA","TURKEY","TURKMENISTAN","TUVALU",
// LETTER - U
"UGANDA","UKRAINE","UNITED ARAB EMIRATES","UAE","UNITED KINGDOM", "UK","UNITED STATES OF AMERICA","USA","URUGUAY","UZBEKISTAN",
// LETTER - V
"VANUATU","VATICAN CITY","HOLY SEE","VENEZUELA","VIETNAM",
// LETTER - Y
"YEMEN",
// LETTER - Z
"ZAMBIA","ZIMBABWE"]

//----------------------------------------------------------------------//
//  ALL CATEGORIES
//----------------------------------------------------------------------//

//----------------------------------------------------------------------//
// CLASSES - Player/Categories   
//----------------------------------------------------------------------//

class Player {
    constructor(player){
        this.player=player;
    }
}
class Rounds {
    constructor(animal,color,state,country,score){
        this.animal=[animal];
        this.color=[color];
        this.state=[state];
        this.country=[country];
        this.score=[score]; 
    }
    round(playerRound){
        playerRound.animal.push(animals)
        playerRound.color.push(colors)
        playerRound.state.push(states)
        playerRound.state.push(country)
        playerRound.score.push(scores)   
    }

}

//----------------------------------------------------------------------//
//  VARIABLES - used in the game    
//----------------------------------------------------------------------//

let newR;
let counterDown = 1000*120
let stopRound = true
let playerChoice = 0;
let single= new Player()
let multiplayer = new Player ("Computer")

let playerRound, singleP, multiP
let gifTime  = 3000
let count = 0
let countPoints = 0
let countRoundNumber =0
let scoreTotal = 0
let countRounds = 1
let timesUp = false
let pcPlay = 0
let pcWord = ""
let pccountPoints = 0
let pcscoreTotal = 0
let pcRound = 0
let stateY=0
let countryY=0
let animalY=0
let colorY=0
let ramdonArray=[]
let ramdonWordCount = 0
let inputBox
let w = 0
let y=0


//----------------------------------------------------------------------//
//  START button function   
//----------------------------------------------------------------------//
const start = () => {
    document.querySelector("#start").remove();
    addButtonsMultiplayer ();
}

//----------------------------------------------------------------------//
//  created multiplayer buttons and onclick     
//----------------------------------------------------------------------//
const addButtonsMultiplayer = ()=> {

    for (let i=0;i<=1;i++){
        let div = document.createElement("div")
        div.setAttribute("id",divPlyer[i])
        let divP = document.querySelector("#players") 
        divP.appendChild(div)
         let btn = document.createElement("button")
         btn.setAttribute("id", divPlyerButton[i])
         btn.setAttribute("class","btn")
         btn.innerHTML = buttonPlayers[i]
         let dRules = document.querySelector(`#${divPlyer[i]}`);
         dRules.appendChild(btn);         
     }
    //create onclick event//
    document.getElementById("btn-rules").addEventListener('click', rules);
    document.getElementById("btn-rule").addEventListener('click', rules);
    document.getElementById("btn-player_1").addEventListener('click', singlePlayer);
    //document.getElementById("btn-player_2").addEventListener('click', multiPlayer);
}
//----------------------------------------------------------------------//
//  RESTART button - reload function
//----------------------------------------------------------------------//
const restart = () => {
    let restart = confirm("Do you want to RESTART STOP");
    if (restart) {
        alert("Let's start over!");
        location.reload()
    } else {
        alert("Good decision!");
    }
}
//----------------------------------------------------------------------//
//  RULES button - new window function    
//----------------------------------------------------------------------//
const rules =()=>{
    window.open("rules.html");
}
//----------------------------------------------------------------------//
//  SINGLE PLAYER - clear screen and add single buttons and inputs
//----------------------------------------------------------------------//
const singlePlayer =()=>{
    let addClass = document.querySelector("#names :nth-child(1)")
    addClass.setAttribute("class","ipt_player_1")

    document.querySelector("#players").remove();
    document.querySelector("#main").style.opacity=0.0;
    
    for (let i=0;i<=1;i++){
        let div = document.createElement("div")
        div.setAttribute("id",divPlayers[i])
        let divP = document.querySelector(".ipt_player_1") 
        divP.appendChild(div)
        if(i==0){
            let ipt = document.createElement("input")
            ipt.setAttribute("id","upt-player_1")
            ipt.setAttribute("type","text")
            ipt.setAttribute("onkeyup","this.value = this.value.toUpperCase()")
            ipt.text = "Type Player 1 Name"
            ipt.setAttribute("value","TYPE PLAYER NAME")
            let dIpt = document.querySelector(`#${divPlayers[i]}`);
            dIpt.appendChild(ipt);
        }else{

         let btn = document.createElement("button")
         btn.setAttribute("id", btnPlayers[i])
         btn.setAttribute("class","btn")
         btn.setAttribute("type","submit")
         btn.innerHTML = "READY"
         
         let dRules = document.querySelector(`#${divPlayers[i]}`);
         dRules.appendChild(btn);    
        }    
     }
     //click event for REDADY button
     document.getElementById("btn-ready_1").addEventListener('click', ready)
}

//----------------------------------------------------------------------//
//  MULTI PLAYER - Second Window for player 2  
//----------------------------------------------------------------------//
const multiPlayer =()=>{
    alert(" hi multi player")
}

//----------------------------------------------------------------------//
//  READY button - loads screen for player 1  
//----------------------------------------------------------------------//
let namePlayer =""
const ready=()=>{
    
    //display as block
    document.querySelector("#playing-game").setAttribute("id","#playing-game_1")

    //get player's name
    namePlayer = document.querySelector("#upt-player_1").value.toUpperCase()
    newPlayer(namePlayer)
    playerChoice=1;
    document.querySelector("#player-name2").innerHTML = "COMPUTER"
    document.querySelector("#player-name").innerHTML = namePlayer
    document.querySelector("#names").remove();    
    document.querySelector("#main").remove();
    document.getElementById("game").style.marginTop = "52%";        
    document.getElementById("game").style.marginBottom="13"
    for(let i of playingID){
    document.getElementById(i).style.color = "black";
    document.getElementById(i).style.border="2px solid black"
    }

    document.getElementById("btn-stop").addEventListener('click', stop);
    randomLetter()
    timer()
    countRound()
    newPlayer(namePlayer)
    alert(`Round ${countRounds} out of 4`)
    document.querySelector("#btn-stop").disabled = false;
    document.getElementById("btn-stop").style.color = "red";
    
}

//----------------------------------------------------------------------//
//  STOP - locks time and categories  
//----------------------------------------------------------------------// 
const stop=()=>{
    if(stopRound){
    alert("STOP!")
    }    
//----------------------------------------------------------------------//
//  Confirm if Animal is in the array and give 10+ 
//----------------------------------------------------------------------// 
    // pcRandomWord()
    let animales = document.querySelector("#animal_1").value
    let word = document.querySelector("#animal_1")
    let comparissonAnimal = document.querySelector("#letter").innerHTML
    let ind = animales[0]

    //compare the letter than the word
    document.querySelector("#animal_1").disabled = true;
    if(ind == comparissonAnimal){
    for(let i=0; i< animalCategory.length;i++){
    if(animalCategory[i] == animales){
        word.style.color="green"
        countPoints+=10 
        i = animalCategory.length
    }else{
        word.style.color="red"
    }  
    }
    } else{

            word.style.color="red"
        }
//----------------------------------------------------------------------//
//  Confirm if color is in the array and give 10+ 
//----------------------------------------------------------------------// 

let colorValue  = document.querySelector("#color_1").value
let wordColor = document.querySelector("#color_1")
let compareColor  = document.querySelector("#letter").innerHTML
let colorFirstLetter = colorValue[0]

//compare the letter than the word
document.querySelector("#color_1").disabled = true;
if(colorFirstLetter == compareColor){
for(let j=0; j< colorCategory.length;j++){
if(colorCategory[j] == colorValue){
    wordColor.style.color="green"
    countPoints+=10 
    j = colorCategory.length
}else{
    wordColor.style.color="red"
}  
}
} else{
        wordColor.style.color="red"
}

//----------------------------------------------------------------------//
//  Confirm if state is in the array and give 10+ 
//----------------------------------------------------------------------// 

    let stateValue  = document.querySelector("#state_1").value
    let stateWord = document.querySelector("#state_1")
    let compareState  = document.querySelector("#letter").innerHTML
    let stateFirstLetter = stateValue[0]
    
    //compare the letter than the word
    document.querySelector("#state_1").disabled = true;
    if(stateFirstLetter == compareState){
    for(let l=0; l< stateCategory.length;l++){
    if(stateCategory[l] == stateValue){
        stateWord.style.color="green"
        countPoints+=10 
        l = stateCategory.length
    }else{
        
        stateWord.style.color="red"
    }  
    }
    } else{
        stateWord.style.color="red"
        }

//----------------------------------------------------------------------//
//  Confirm if country is in the array and give 10+ 
//----------------------------------------------------------------------// 
    
    let countryValue  = document.querySelector("#country_1").value
    let countryWord = document.querySelector("#country_1")
    let countryCompare = document.querySelector("#letter").innerHTML
    let countryFirstLetter = countryValue[0]
    
    //compare the letter than the word
    document.querySelector("#country_1").disabled = true;
    if(countryFirstLetter == countryCompare){
    for(let l=0; l< countryCategory.length;l++){
    if(countryCategory[l] == countryValue){
        countryWord.style.color="green"
        countPoints+=10 
        l = countryCategory.length
    }else{
        countryWord.style.color="red"
    }  
    }
    } else{
            countryWord.style.color="red"
        }


//----------------------------------------------------------------------//
//  add points to Score 
//----------------------------------------------------------------------// 
       //player 1
    scoreTotal += countPoints

    document.querySelector("#score_1").setAttribute("value", countPoints)
    let scoress = document.querySelector("#score_1").value
    document.querySelector("#scoreTop").setAttribute("value", scoreTotal)
    document.getElementById("scoreTop").innerHTML = `Total: ${scoreTotal}`


//----------------------------------------------------------------------//
//  add to class 
//----------------------------------------------------------------------//    
    newRound(animales,colorValue,stateValue,countryValue,scoress)
    // newR.compareWOrds(single)

//----------------------------------------------------------------------//
//  COMPUTER ANIMAL FIELD
//----------------------------------------------------------------------//    

let gameLetter = document.querySelector("#letter").innerHTML
    let animalArray=[]
            //random 0 or 1 - for the computer to play
            pcPlay = Math.floor(Math.random() * 2)
            let inputAnimal = `a-${animalY}`

            if (pcPlay == 0) {

                //each item in the category
                for (let x of animalCategory) {

                    //check if first letter match game letter 
                    if (x[0] == gameLetter) {
                        //push the word to array
                        animalArray[ramdonWordCount] = x
                        ramdonWordCount++
                    }
                }
               
                //create new variable to store the random value
                let pcRandomWord = animalArray[Math.floor(Math.random() * animalArray.length)]
                animalArray=[]
                ramdonWordCount=0
    
                
                if (pcRandomWord===undefined) {
                    pcWord = document.querySelector(`#${inputAnimal}`)
                    pcWord.style.color = "orange"
                    document.querySelector(`#${inputAnimal}`).setAttribute("value", "NO WORD")
                } else {
                    //
                    document.querySelector(`#${inputAnimal}`).setAttribute("value", pcRandomWord)
    
                    pcWord = document.querySelector(`#${inputAnimal}`)
                    pcWord.style.color = "green"
                    pccountPoints += 10
                } 
            }
            else {
    
                pcWord = document.querySelector(`#${inputAnimal}`)
                document.querySelector(`#${inputAnimal}`).setAttribute("value", "YOU GOT ME!")
                
                pcWord.style.color = "red"
                
            }
            animalY++
//----------------------------------------------------------------------//
//  COMPUTER COLOR FIELD
//----------------------------------------------------------------------//
let colorRamdonArray=[]
            //random 0 or 1 - for the computer to play
            pcPlay = Math.floor(Math.random() * 2)
           let inputColor = `c-${colorY}`
            if (pcPlay == 0) {
                
                //each item in the category
                for (let x of colorCategory) {

                    //check if first letter match game letter 
                    if (x[0] == gameLetter) {
                        //push the word to array
                        colorRamdonArray[ramdonWordCount] = x
                        ramdonWordCount++
                    }
                }
    
                //create new variable to store the random value
                let pcRandomWord = colorRamdonArray[Math.floor(Math.random() * colorRamdonArray.length)]

                colorRamdonArray=[]
                ramdonWordCount=0
    
                if (pcRandomWord===undefined) {
                    pcWord = document.querySelector(`#${inputColor}`)
                    pcWord.style.color = "orange"
                    document.querySelector(`#${inputColor}`).setAttribute("value", "NO WORD")
                } else {
                    //
                    document.querySelector(`#${inputColor}`).setAttribute("value", pcRandomWord)
    
                    pcWord = document.querySelector(`#${inputColor}`)
                    pcWord.style.color = "green"
                    pccountPoints += 10
                } 
            }
            else {
    
                pcWord = document.querySelector(`#${inputColor}`)
                document.querySelector(`#${inputColor}`).setAttribute("value", "YOU GOT ME!")
                
                pcWord.style.color = "red"
                
            }
            colorY++

//----------------------------------------------------------------------//
//  COMPUTER STATE FIELD
//----------------------------------------------------------------------//
let stateArray=[]
        //random 0 or 1 - for the computer to play
        pcPlay = Math.floor(Math.random() * 2)

        let inputState = `s-${stateY}`
        if (pcPlay == 0) {

            //each item in the category
            for (let x of stateCategory) {

                //check if first letter match game letter 
                if (x[0] == gameLetter) {
                    //push the word to array
                    stateArray[ramdonWordCount] = x
                    ramdonWordCount++

                }
            }

            //create new variable to store the random value

            let pcRandomWord = stateArray[Math.floor(Math.random() * stateArray.length)]

            stateArray=[]
            ramdonWordCount=0
            if (pcRandomWord===undefined) {
                pcWord = document.querySelector(`#${inputState}`)
                pcWord.style.color = "orange"
                document.querySelector(`#${inputState}`).setAttribute("value", "NO WORD")
                stateY++
            } else {
                //
                document.querySelector(`#${inputState}`).setAttribute("value", pcRandomWord)

                pcWord = document.querySelector(`#${inputState}`)
                pcWord.style.color = "green"
                pccountPoints += 10

                stateY++
            } 
        }
        else {

            pcWord = document.querySelector(`#${inputState}`)
            document.querySelector(`#${inputState}`).setAttribute("value", "YOU GOT ME!")
            
            pcWord.style.color = "red"
            stateY++
        }
//----------------------------------------------------------------------//
//  COMPUTER COUNTRY FIELD
//----------------------------------------------------------------------//

let contryArray=[]
pcPlay = Math.floor(Math.random() * 2)

let inputCountry = `co-${countryY}`
if (pcPlay == 0) {
    
    //each item in the category
    for (let x of countryCategory) {
        //check if first letter match game letter 
        if (x[0] == gameLetter) {
            //push the word to array
            contryArray[ramdonWordCount] = x
            ramdonWordCount++

        }
    }

    //create new variable to store the random value

    let pcRandomWord = contryArray[Math.floor(Math.random() * contryArray.length)]


    if (pcRandomWord===undefined) {
        pcWord = document.querySelector(`#${inputCountry}`)
        pcWord.style.color = "orange"
        document.querySelector(`#${inputCountry}`).setAttribute("value", "NO WORD")
    } else {
        //
        document.querySelector(`#${inputCountry}`).setAttribute("value", pcRandomWord)

        pcWord = document.querySelector(`#${inputCountry}`)
        pcWord.style.color = "green"
        pccountPoints += 10

    } 
}
else {

    pcWord = document.querySelector(`#${inputCountry}`)
    document.querySelector(`#${inputCountry}`).setAttribute("value", "YOU GOT ME!")
    
    pcWord.style.color = "red"
    
}


countryY++
//----------------------------------------------------------------------//
//  SUM'S COMPUTER POINTS
//----------------------------------------------------------------------//  


pcRound += 1
  
pcscoreTotal += pccountPoints
let inputScore = `sc-${w}`

document.querySelector(`#${inputScore}`).setAttribute("value", pccountPoints)
// document.querySelector("#scoreTop2").setAttribute("value", pcscoreTotal)
document.getElementById("scoreTop2").innerHTML = `Total: ${pcscoreTotal}`
ramdonArray = []
ramdonWordCount = 0
pccountPoints = 0
w++

//----------------------------------------------------------------------//
//  stop clock 
//----------------------------------------------------------------------//  
    stopRound=false;

//----------------------------------------------------------------------//
//  CHANGE IDS AND ADD NEW ROW
//----------------------------------------------------------------------//  
//extra - make it cleaner
document.getElementById("animal_1").setAttribute("id","animal_0")
document.getElementById("color_1").setAttribute("id","color_0")
document.getElementById("state_1").setAttribute("id","state_0")
document.getElementById("country_1").setAttribute("id","country_0")
document.getElementById("score_1").setAttribute("id","score_0")

document.getElementById("li-animal").setAttribute("id","li-animal_1")
document.getElementById("li-color").setAttribute("id","li-color_1")
document.getElementById("li-state").setAttribute("id","li-state_1")
document.getElementById("li-country").setAttribute("id","li-country_1")
document.getElementById("li-score").setAttribute("id","li-score_1")

countRounds+=1

addRewRow()
addRoundAlert()

if(countRounds==5)
{
    pcScore = document.querySelector("#scoreTop2").value
    if(scoreTotal>pcscoreTotal){
        alert(`${namePlayer} is the WINNER wiht ${scoreTotal} points`)
    }else{
    alert(`COMPUTER is the WINNER wiht ${pcscoreTotal} points`)}
    document.getElementById("round").setAttribute("type","button")
    document.getElementById("round").innerHTML = "RESTART"
    document.getElementById("round").addEventListener('click', restart);
}
    }


//----------------------------------------------------------------------//
//  Creates a random LETTER for the game  
//----------------------------------------------------------------------//
const randomLetter = ()=>{
    const alphabet = "abcdefghijklmnopqrstuvwxyz"
    let ramdonLetter = alphabet[Math.floor(Math.random() * alphabet.length)]
    document.getElementById("letter").innerHTML = ramdonLetter.toUpperCase()
}

//----------------------------------------------------------------------//
//   TIMER count down 
//----------------------------------------------------------------------//
const timer =()=>{
    // Update the count down every 1 second
    let x = setInterval(function() {        
        counterDown-=1000;
        let minutes = Math.floor((counterDown % (1000 * 60 * 60)) / (1000 * 60));
        let seconds = Math.floor((counterDown % (1000 * 60)) / 1000);

    // Display the result 
    document.getElementById("timer").innerHTML = "TIMER : "+minutes+" : "+ seconds;
    
    // If the count down is finished, write some text
    if (counterDown < 0 ) {
      clearInterval(x);
      document.getElementById("timer").innerHTML = "EXPIRED";
      counterDown = 1000*120
      document.querySelector("#animal_1").disabled = true;
      document.querySelector("#color_1").disabled = true;
      document.querySelector("#state_1").disabled = true;
      document.querySelector("#country_1").disabled = true;
      timesUp=true
      stopRound = true
    //   alert("time's up - Press STOP to start a new round!")
    }
    // If press STOP button, stops the timer and display it
    if (stopRound==false){
        document.getElementById("timer").innerHTML = "TIMER : "+minutes+" : "+ seconds;
        clearInterval(x);
        stopRound = true
        timesUp=false
        counterDown = 1000*120
    }
    if(timesUp){
        alert("time's up - Press STOP to start a new round!")
    }
  }, 1000); 
}

//----------------------------------------------------------------------//
//   Changes round number 
//----------------------------------------------------------------------//
const countRound = ()=>{
    count+=1
    document.getElementById("round").innerHTML = `ROUND: ${count}`

}
//----------------------------------------------------------------------//
//   Add to class Round 
//----------------------------------------------------------------------//
const newRound = (animal,color,state,country,score)=>{
    newR = new Rounds(animal,color,state,country,score)
}

//----------------------------------------------------------------------//
//   Add to class Player Single 
//----------------------------------------------------------------------//
const newPlayer = (newP)=>{
    single = new Player(newP)
}


//----------------------------------------------------------------------//
//   ADD NEW ROW
//----------------------------------------------------------------------//

// const liNewRow =[]

const addRewRow =()=>{

 countRoundNumber+=1

    if (countRoundNumber <= 3) {

        for (let i = 0; i <= 4; i++) {
            //new li
            let newLi = document.createElement("li")
            newLi.setAttribute("id", liNewCategories[i])
            let olCat = document.querySelector(`#${olCategories[i]}`)
            olCat.appendChild(newLi)
            //new input
            let inputNewRow = document.createElement("input")
            inputNewRow.setAttribute("id", inputCategories[i])
            inputNewRow.setAttribute("class", "li")
            let liCat = document.querySelector(`#${liNewCategories[i]}`)
            liCat.appendChild(inputNewRow)
            inputNewRow.setAttribute("onkeyup", "this.value = this.value.toUpperCase()")

            if (i == 4) {
                document.querySelector("#score_1").disabled = true;
            }
        }
        countRound()
        timer()
        randomLetter()
        countPoints = 0
    }

}


//----------------------------------------------------------------------//
//   ROUND ALERT 
//----------------------------------------------------------------------//

    const addRoundAlert = () => {
        
     if (countRounds == 4) {
            alert(`This is FINAL ROUND!`)
     }if (countRounds == 5){
            document.querySelector("#btn-stop").disabled = true;
        }
    }

const pcIdCategories = ["animal2","color2","state2","country2","score2"]
const pcIdRow1 = ["a-","c-","s-","co-"]
const allCategories = [animalCategory,colorCategory,stateCategory,countryCategory]
//----------------------------------------------------------------------//
//   PC ramdon 
//----------------------------------------------------------------------//










